sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-contentFilter-plugin
    all_branches: true
env:
  global:
  - secure: LLrZQErEMCpfw7ezZLDNxxasAEhMnQoSuZJC9RdfiVgMiQILPp6u7nTjeu7uJBW+9gxGK8/RR8oevg/zCUBa0ai3GX4VgkySVn7OMO+krCsEAa+ebz6kw65YbK0XSxX8T4amAdq50++76Fsl+PBIdr4IKFtpLDH5qe5VZe28uw6RmUNtXjUcwh4kzo/wS6nZQxSIQ0U0aPq5R4bZ/3PUNJ10/dQBO17yxdibtoNjwhzkajQB+3grXWz8ICWAsd3/HEUCLYGVVtG9omamOFBatys/br6KY44CZwYqYIGdRo5TSCbHAQ+9X3Z3KYqjH2fCu48QKexjxkq2cveTE5SHvLApW9zBEYj4ptrAM+ohpIq1Fv6uXWIjRvI4DOOexaV2t+sZndXv6oQ0QLfQRxmNbmbmxp4dlZSj3qFvKoeBVxPJk+cjovag55S5/915rs+VyzVUpoFplStcS/JQCOXPdEEhlqjV+RODTEKLCrFsrTgyTzbpp3f2dS0zznr9eoWrM17YgzvbXbhJpUFBton1NxVW0f1/pgxcYrWILn2n1b4b8WR25ik2aSNrMIiQxnrVSLbBgmoUBjblxjDXMphudpxVHgZm9yBPJdGGOPyRxogyWBByl61EMm7dCh6TW1nIjlRZnaVi5D8t8qof2bNZeb3GoRPcK0J1u8wTWSfI/eg=
  - secure: dFBkvLQsI5RPJpb5IFnPMiQCLACv/F5q02i6CVaS5k/cH946JJswbwOSJbZTow3u503NcxITXcHA60qQddnEUHZP/n9T2ssFPKT4zlxnUpd9E+ZbArR21jSaSqAJaBinieyFDTQEvKS81AlWTmXhpvsuF6jjDp2K8a4rHP97Ew/k0AEP8akwgWxR8zjzDQoOaPW8xIYHpEXqt2eoaBRh/I8k9Zfv6CVIfd6H6d53AK9/JUZV+65ID2XEk2yapldHuqS3+tC1KBsg1pe5tSQySxx5z34MaxGd+GKUTARo41cP6KhBLaaA8aTyltI/4JTqbcJjbr/CPqL18mZVqn+xd40G5cYQmIALs1uo46hFZr072YkPjbnTBbYWgjkpGSBpcRb7ek/MNE4qmjCfTAxrmwgX9rFruNbr5xwiEsbgCVxARNTv+K/Jw1LK8BIe/LRg6NpD6l8nQ0UXPD8aK0N41yQP0CZrKo2lzKl6jIVkDdl6QpLKWj1MQjJYAkb5gjzsVNpbWHAJ2MjqPos0f0CWvM4NMorzHmqohpWw2aQgJWubW5Tylkpbz6j7nDBlmzu5Ro+r9xGGtoqtO60QZAe1w6ewH7RPaKyZwfHamE+Yjm1+Lp7WKN/54VuSw/3xu7gH/G+rD7ODcuK4+JCJkufSCfLoK+2R1UvQVn0EXdetQXw=
